import type { Metadata } from "next";
import { Space_Grotesk, Inter, JetBrains_Mono } from "next/font/google";
import { MotionConfig } from "framer-motion";
import { ThemeProvider, themeInitScript } from "@/components/theme/ThemeProvider";
import { ChatLauncher } from "@/components/chatbot/ChatLauncher";
import { ChatWidget } from "@/components/chatbot/ChatWidget";
import { ChatWidgetProvider } from "@/components/chatbot/ChatWidgetProvider";
import { ScrollProgress } from "@/components/ui";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["700"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <head>
        {/* Blocking inline script: applies the stored theme before first paint to avoid a flash of the wrong theme. */}
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        {/*
         * reducedMotion="user" makes every motion component respect the OS
         * prefers-reduced-motion setting automatically at the animation
         * engine level, so components render the *same* variants/styles on
         * server and client (fixing SSR/hydration mismatches) instead of
         * each component branching on useReducedMotion() to pick a
         * different "hidden" style object per environment.
         */}
        <MotionConfig reducedMotion="user">
          <ThemeProvider>
            <ScrollProgress />
            <ChatWidgetProvider>
              {children}
              <ChatLauncher />
              <ChatWidget />
            </ChatWidgetProvider>
          </ThemeProvider>
        </MotionConfig>
      </body>
    </html>
  );
}
